# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68fe6e39df2750dd47b3dd095fe7eac3ee1e15d22be0b136726f3e0748403d2f1af5963b09dbbd5f07de3e43a6195abdc15885a74611bda4faf4a19ae616e90a

test:
  secret_key_base: 1a832cf137720084a168470a37cffe0d244e46ef4b05897f1b91b039499e74dc6a747e0cd152ef91a17e00673f34f2c1241245f8588d5fea1c67e04a138638ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
